"""
clahe_prep.py  --  CSC3014 Project Part 2, Track A (G17)

Builds a CLAHE-preprocessed mirror of the Roboflow Malaysian food dataset.

Contrast Limited Adaptive Histogram Equalisation is applied to the L (lightness)
channel in LAB colour space only. The a/b chroma channels are left untouched so
that hue is preserved -- food colour is a detection cue and must not drift.

Labels are copied verbatim: CLAHE changes pixel intensities, never geometry, so
every bounding box remains valid.

Usage (from C:\\Users\\PF4B3\\Desktop\\g17):
    python clahe_prep.py
    python clahe_prep.py --clip 3.0 --tiles 8
"""

import argparse
import shutil
import sys
from pathlib import Path

import cv2
import numpy as np

HERE = Path(__file__).resolve().parent
SRC_ROOT = HERE / "dataset"
DST_ROOT = HERE / "dataset_clahe"
SPLITS = ("train", "valid", "test")
IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".bmp"}

CLASS_NAMES = [
    "Anchovies", "Boiled-Egg", "Char-Kuey-Teow", "Chicken-Rendang",
    "Curry-Puff", "Fried-Chicken", "Fried-Egg", "Fried-Rice",
    "Hokkien-Mee", "Lo-Mein", "Mee-Rebus", "Mee-Siam",
    "Peanuts", "Rice", "Roti-Canai", "Sambal", "Slices-Cucumber",
]


def equalise(bgr, clahe):
    """Apply CLAHE to lightness only, leaving chroma alone."""
    lab = cv2.cvtColor(bgr, cv2.COLOR_BGR2LAB)
    lab[:, :, 0] = clahe.apply(lab[:, :, 0])
    return cv2.cvtColor(lab, cv2.COLOR_LAB2BGR)


def gather(split):
    """Yield every image path in a split, sorted for reproducibility."""
    folder = SRC_ROOT / split / "images"
    if not folder.is_dir():
        sys.exit(f"missing folder: {folder}")
    found = [p for p in sorted(folder.iterdir()) if p.suffix.lower() in IMAGE_SUFFIXES]
    if not found:
        sys.exit(f"no images found in {folder}")
    return found


def process_split(split, clahe, samples):
    src_images = gather(split)
    dst_images = DST_ROOT / split / "images"
    dst_labels = DST_ROOT / split / "labels"
    dst_images.mkdir(parents=True, exist_ok=True)
    dst_labels.mkdir(parents=True, exist_ok=True)

    written, skipped = 0, 0

    for index, src in enumerate(src_images):
        raw = cv2.imread(str(src), cv2.IMREAD_COLOR)
        if raw is None:
            print(f"  unreadable, skipping: {src.name}")
            skipped += 1
            continue

        out = equalise(raw, clahe)
        cv2.imwrite(str(dst_images / src.name), out)

        label_src = SRC_ROOT / split / "labels" / f"{src.stem}.txt"
        if label_src.exists():
            shutil.copy2(label_src, dst_labels / label_src.name)
        else:
            print(f"  no label for: {src.name}")

        # keep a handful of before/after pairs for the report figure
        if split == "test" and index < 3:
            pair = np.hstack([raw, out])
            cv2.imwrite(str(HERE / f"clahe_sample_{index}.jpg"), pair)
            samples.append(src.name)

        written += 1

    return written, skipped


def write_yaml(clip, tiles):
    root = str(DST_ROOT).replace("\\", "/")
    lines = [
        f"path: {root}",
        "train: train/images",
        "val: valid/images",
        "test: test/images",
        "",
        f"nc: {len(CLASS_NAMES)}",
        f"names: {CLASS_NAMES}",
        "",
        f"# CLAHE mirror of dataset/  clipLimit={clip}  tileGridSize=({tiles},{tiles})",
        "# generated by clahe_prep.py -- L channel of LAB only, chroma preserved",
    ]
    target = DST_ROOT / "data.yaml"
    target.write_text("\n".join(lines) + "\n")
    return target


def main():
    parser = argparse.ArgumentParser(description="CLAHE mirror of the food dataset")
    parser.add_argument("--clip", type=float, default=2.0, help="clip limit")
    parser.add_argument("--tiles", type=int, default=8, help="tile grid is N x N")
    args = parser.parse_args()

    clahe = cv2.createCLAHE(clipLimit=args.clip, tileGridSize=(args.tiles, args.tiles))
    samples = []
    totals = {}

    print(f"source: {SRC_ROOT}")
    print(f"target: {DST_ROOT}")
    print(f"clipLimit={args.clip}  tileGridSize=({args.tiles},{args.tiles})\n")

    for split in SPLITS:
        print(f"{split} ...")
        written, skipped = process_split(split, clahe, samples)
        totals[split] = written
        print(f"  {written} written, {skipped} skipped\n")

    yaml_path = write_yaml(args.clip, args.tiles)

    print("-" * 46)
    for split, count in totals.items():
        print(f"{split:>6}: {count}")
    print(f" total: {sum(totals.values())}")
    print(f"\nyaml:    {yaml_path}")
    if samples:
        print("samples: clahe_sample_0.jpg .. clahe_sample_2.jpg (before | after)")
        print(f"         from {', '.join(samples)}")


if __name__ == "__main__":
    main()
